---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  labels:
    grafana_datasource: "true"
  disableNameSuffixHash: true
configMapGenerator:
  - name: grafana-datasources
    files:
      - ./loki.yaml
      - ./prometheus.yaml
