---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./alloy.yaml
  - ./exporters
  - ./grafana.yaml
  - ./loki.yaml
  - ./mimir.yaml
  - ./namespace.yaml
  - ./repository.yaml
